[package]
name = "qorb"
version = "0.0.0"
edition = "2021"
description = "Connection Pooling"
license = "MPL-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
debug-ignore = "1.0"
derive-where = "1.2"
thiserror = "1.0"
tokio = { version = "1.37.0", features = ["macros", "sync", "rt"] }
