[package]
name = "reqorb"
version = "0.1.0"
edition = "2024"
description = "glues reqwest onto qorb (somewhat unpleasantly)"
license = "MPL-2.0"

[dependencies]
async-trait = { workspace = true }
qorb = { workspace = true }
reqwest = { workspace = true }
